/* eslint-disable max-len */
export default [
  'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi a tempus velit. Sed libero lorem, lacinia vitae nulla quis, vulputate tincidunt ante. Interdum et malesuada fames ac ante ipsum primis in faucibus. Integer rutrum condimentum massa eu sodales. Mauris vel egestas felis. Crash dignissim nibh vitae sapien ornare, nec aliquam ex placers. Praesent a erat mauris. Duis rutrum ante non dapibus consectetur. Fusce ultrices gravida felis, non cursus elit malesuada sed. Etiam efficitur libero sit amet sodales consectetur.',
  'Nullam hendrerit, augue a posuere accumsan, ligula mauris auctor nisl, consectetur semper nisl nisi at nisl. Proin venenatis neque vitae imperdiet tincidunt. Interdum et malesuada fames ac ante ipsum primis in faucibus. Etiam feugiat placerat quam, nec convallis lectus scelerisque eget. In sed imperdiet neque, ac condimentum erat. Pellentesque nulla justo, finibus sed risus aliquet, ultricies ultrices lectus. Ut neque orci, fringilla non mi non, egestas tempor lacus.',
  'Proin tincidunt, diam in consectetur posuere, diam nunc faucibus dui, nec tempus nunc libero nec ligula. Nulla rutrum elementum erat. Vestibulum ut placerat lorem. Phasellus enim dui, sodales at risus ac, vulputate venenatis nisl. Cras cursus ante a vulputate sagittis. Mauris in tempor metus, et ultrices nulla. Vestibulum nec purus sem.',
  'Morbi sollicitudin dignissim libero, at pulvinar magna venenatis eget. Donec est urna, mollis non pretium at, condimentum a ante. Ut placerat porttitor ante quis tempor. Curabitur sit amet magna ante. Mauris metus velit, placerat eget elementum a, bibendum eget enim. Ut sit amet efficitur augue. Nam id mi consequat, maximus ipsum vel, varius mi. Nullam vitae efficitur turpis. Integer vestibulum dolor eu arcu faucibus, ut bibendum ligula cursus. Ut blandit ullamcorper enim. Pellentesque eu nisi enim. Integer consectetur lacus quam, eget condimentum ipsum venenatis quis. Maecenas posuere tempus ligula vitae molestie. Phasellus ultricies, ligula a rutrum pellentesque, orci enim elementum lorem, eu lobortis nunc ligula at velit.',
  'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi a tempus velit. Sed libero lorem, lacinia vitae nulla quis, vulputate tincidunt ante. Interdum et malesuada fames ac ante ipsum primis in faucibus. Integer rutrum condimentum massa eu sodales. Mauris vel egestas felis. Cras dignissim nibh vitae sapien ornare, nec aliquam ex placerat. Praesent a erat mauris. Duis rutrum ante non dapibus consectetur. Fusce ultrices gravida felis, non cursus elit malesuada sed. Etiam efficitur libero sit amet sodales consectetur.',
  'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi a tempus velit. Sed libero lorem, lacinia vitae nulla quis, vulputate tincidunt ante. Interdum et malesuada fames ac ante ipsum primis in faucibus. Integer rutrum condimentum massa eu sodales. Mauris vel egestas felis. Cras dignissim nibh vitae sapien ornare, nec aliquam ex placerat. Praesent a erat mauris. Duis rutrum ante non dapibus consectetur. Fusce ultrices gravida felis, non cursus elit malesuada sed. Etiam efficitur libero sit amet sodales consectetur.',
  'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi a tempus velit. Sed libero lorem, lacinia vitae nulla quis, vulputate tincidunt ante. Interdum et malesuada fames ac ante ipsum primis in faucibus. Integer rutrum condimentum massa eu sodales. Mauris vel egestas felis. Cras dignissim nibh vitae sapien ornare, nec aliquam ex placerat. Praesent a erat mauris. Duis rutrum ante non dapibus consectetur. Fusce ultrices gravida felis, non cursus elit malesuada sed. Etiam efficitur libero sit amet sodales consectetur.',
  'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi a tempus velit. Sed libero lorem, lacinia vitae nulla quis, vulputate tincidunt ante. Interdum et malesuada fames ac ante ipsum primis in faucibus. Integer rutrum condimentum massa eu sodales. Mauris vel egestas felis. Cras dignissim nibh vitae sapien ornare, nec aliquam ex placerat. Praesent a erat mauris. Duis rutrum ante non dapibus consectetur. Fusce ultrices gravida felis, non cursus elit malesuada sed. Etiam efficitur libero sit amet sodales consectetur.',
  'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi a tempus velit. Sed libero lorem, lacinia vitae nulla quis, vulputate tincidunt ante. Interdum et malesuada fames ac ante ipsum primis in faucibus. Integer rutrum condimentum massa eu sodales. Mauris vel egestas felis. Cras dignissim nibh vitae sapien ornare, nec aliquam ex placerat. Praesent a erat mauris. Duis rutrum ante non dapibus consectetur. Fusce ultrices gravida felis, non cursus elit malesuada sed. Etiam efficitur libero sit amet sodales consectetur.',
  'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi a tempus velit. Sed libero lorem, lacinia vitae nulla quis, vulputate tincidunt ante. Interdum et malesuada fames ac ante ipsum primis in faucibus. Integer rutrum condimentum massa eu sodales. Mauris vel egestas felis. Cras dignissim nibh vitae sapien ornare, nec aliquam ex placerat. Praesent a erat mauris. Duis rutrum ante non dapibus consectetur. Fusce ultrices gravida felis, non cursus elit malesuada sed. Etiam efficitur libero sit amet sodales consectetur.',
  'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi a tempus velit. Sed libero lorem, lacinia vitae nulla quis, vulputate tincidunt ante. Interdum et malesuada fames ac ante ipsum primis in faucibus. Integer rutrum condimentum massa eu sodales. Mauris vel egestas felis. Cras dignissim nibh vitae sapien ornare, nec aliquam ex placerat. Praesent a erat mauris. Duis rutrum ante non dapibus consectetur. Fusce ultrices gravida felis, non cursus elit malesuada sed. Etiam efficitur libero sit amet sodales consectetur.',
  'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi a tempus velit. Sed libero lorem, lacinia vitae nulla quis, vulputate tincidunt ante. Interdum et malesuada fames ac ante ipsum primis in faucibus. Integer rutrum condimentum massa eu sodales. Mauris vel egestas felis. Cras dignissim nibh vitae sapien ornare, nec aliquam ex placerat. Praesent a erat mauris. Duis rutrum ante non dapibus consectetur. Fusce ultrices gravida felis, non cursus elit malesuada sed. Etiam efficitur libero sit amet sodales consectetur.',
  'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi a tempus velit. Sed libero lorem, lacinia vitae nulla quis, vulputate tincidunt ante. Interdum et malesuada fames ac ante ipsum primis in faucibus. Integer rutrum condimentum massa eu sodales. Mauris vel egestas felis. Cras dignissim nibh vitae sapien ornare, nec aliquam ex placerat. Praesent a erat mauris. Duis rutrum ante non dapibus consectetur. Fusce ultrices gravida felis, non cursus elit malesuada sed. Etiam efficitur libero sit amet sodales consectetur.',
];
